# name: Semgrep

# on:

#   pull_request: {}

#   push:
#     branches: ["master", "main"]
#     paths:
#     - .github/workflows/semgrep.yml

# jobs:
#   semgrep:    
#       runs-on: ubuntu-latest
#       steps:
#       - uses: actions/checkout@v4
#       - name: Set up Python 3.11.4
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.11.4
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install semgrep 
#       - name: Checkout-repo
#         uses: actions/checkout@v4     
#       - name: Run Semgrep
#         env:
#           SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
#         run: |
#           semgrep ci
